export const questions = [
  { number: 1, text: "Build kitchen cabinets", area: "R" },
  { number: 2, text: "Lay brick or tile", area: "R" },
  { number: 3, text: "Repair household appliances", area: "R" },
  { number: 4, text: "Raise fish in a hatchery", area: "R" },
  { number: 5, text: "Assemble electronic parts", area: "R" },
  { number: 6, text: "Drive a truck to deliver packages to offices and homes", area: "R" },
  { number: 7, text: "Test the quality of parts before they are used in fuel cell engines", area: "R" },
  { number: 8, text: "Repair and maintain automobile engines", area: "R" },
  { number: 9, text: "Operate a grinding machine in a factory", area: "R" },
  { number: 10, text: "Fix a leaky faucet", area: "R" },
  { number: 11, text: "Develop a new medicine", area: "I" },
  { number: 12, text: "Study ways to reduce water pollution", area: "I" },
  { number: 13, text: "Conduct chemical experiments", area: "I" },
  { number: 14, text: "Study the movement of planets", area: "I" },
  { number: 15, text: "Examine blood samples using a microscope", area: "I" },
  { number: 16, text: "Investigate the cause of a fire", area: "I" },
  { number: 17, text: "Develop a way to better predict the weather", area: "I" },
  { number: 18, text: "Work in a biology lab", area: "I" },
  { number: 19, text: "Invent a replacement for sugar", area: "I" },
  { number: 20, text: "Do laboratory tests to identify diseases", area: "I" },
  { number: 21, text: "Write books or plays", area: "A" },
  { number: 22, text: "Play a musical instrument", area: "A" },
  { number: 23, text: "Compose or arrange music", area: "A" },
  { number: 24, text: "Draw pictures", area: "A" },
  { number: 25, text: "Create special effects for movies", area: "A" },
  { number: 26, text: "Paint sets for plays", area: "A" },
  { number: 27, text: "Write scripts for movies or television shows", area: "A" },
  { number: 28, text: "Perform a role in a movie or television show", area: "A" },
  { number: 29, text: "Sing in a band", area: "A" },
  { number: 30, text: "Edit movies", area: "A" },
  { number: 31, text: "Teach an individual an exercise routine", area: "S" },
  { number: 32, text: "Help people with personal or emotional problems", area: "S" },
  { number: 33, text: "Give career guidance to people", area: "S" },
  { number: 34, text: "Perform rehabilitation therapy", area: "S" },
  { number: 35, text: "Do volunteer work at a non-profit organization", area: "S" },
  { number: 36, text: "Teach children how to read", area: "S" },
  { number: 37, text: "Help elderly people with their daily activities", area: "S" },
  { number: 38, text: "Work as a playground worker", area: "S" },
  { number: 39, text: "Teach sign language to people with hearing disabilities", area: "S" },
  { number: 40, text: "Help conduct a group therapy session", area: "S" },
  { number: 41, text: "Buy and sell stocks and bonds", area: "E" },
  { number: 42, text: "Manage a retail store", area: "E" },
  { number: 43, text: "Operate a beauty shop or barber shop", area: "E" },
  { number: 44, text: "Manage a department within a large company", area: "E" },
  { number: 45, text: "Start your own business", area: "E" },
  { number: 46, text: "Negotiate business contracts", area: "E" },
  { number: 47, text: "Represent a client in a lawsuit", area: "E" },
  { number: 48, text: "Market a new line of clothing", area: "E" },
  { number: 49, text: "Sell merchandise at a department store", area: "E" },
  { number: 50, text: "Manage a clothing store", area: "E" },
  { number: 51, text: "Develop a spreadsheet using computer software", area: "C" },
  { number: 52, text: "Proofread records or manuscripts", area: "C" },
  { number: 53, text: "Install software across computers on a large network", area: "C" },
  { number: 54, text: "Operate a calculator", area: "C" },
  { number: 55, text: "Keep shipping and receiving records", area: "C" },
  { number: 56, text: "Calculate the wages of employees", area: "C" },
  { number: 57, text: "Inventory supplies using a handheld computer", area: "C" },
  { number: 58, text: "Record rent payments", area: "C" },
  { number: 59, text: "Keep inventory records", area: "C" },
  { number: 60, text: "Enter information into a database", area: "C" }
];